version: '2'

services:
  node:
    image: node:argon
    env_file: .env
    working_dir: /usr/src/app
    links:
      - redis
    volumes:
      - .:/usr/src/app
    command: npm start
    environment:
      - CRON_INTERVAL=*/60 * * * * *
      - OFFLINE_THRESH=1
      - IRC_CHANNEL=#jenkins-monitor-dev
      - IRC_SERVER=chat.freenode.net
      - IRC_USER=jenkins-monitor-dev
      - JENKINS_URL=https://ci.nodejs.org
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=silent
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false

  redis:
    image: redis:3
