dev:
    image: node:slim
    env_file: .env.dev
    working_dir: /usr/src/app
    links:
        - redis
    volumes:
        - .:/usr/src/app
    command: npm start
    environment:
        - CRON_INTERVAL=*/15 * * * * *
        - JENKINS_URL=https://ci.nodejs.org
        - NODE_ENV=development

redis:
    image: redis
