dev:
    image: node:argon
    env_file: .env.dev
    working_dir: /usr/src/app
    links:
        - redis
    volumes:
        - .:/usr/src/app
    command: npm start
    environment:
        - CRON_INTERVAL=*/60 * * * * *
        - IRC_CHANNEL=#jenkins-monitor-dev
        - IRC_SERVER=chat.freenode.net
        - IRC_USER=jenkins-monitor-dev
        - JENKINS_URL=https://ci.nodejs.org
        - NODE_ENV=development

redis:
    image: redis
