dev:
    image: iojs:slim
    env_file: .env.dev
    working_dir: /usr/src/app
    links:
        - redis
    volumes:
        - .:/usr/src/app
    command: npm run watch
    environment:
        - CRON_INTERVAL=*/15 * * * * *

redis:
    image: redis
